### ISSUE TITLE
add support for emptyRDD method of SparkContext

### ISSUE THREAD

**Issue by simonjscott** [dwestheide/kontextfrei#62]
Spark distinguishes:

`sc.parallelize(Seq.empty[T])`

from 
`sc.emptyRDD[T]`

(The former gives an RDD of T with empty partitions, whereas the latter gives an RDD with no partitions).

Propose we should have `DCollectionConstructors.empty` as well as `DCollectionConstructors.unit` to allow this distinction to be expressed by users of this library.

**Comment by dwestheide** [comment]
That sounds good! :+1:

**Comment by dwestheide** [comment]
Implemented in #63

**Comment by dwestheide** [comment]
This has been released [kontextfrei 0.8.0](https://github.com/dwestheide/kontextfrei/releases/tag/v0.8.0)
