### ISSUE TITLE
Add 'partitionBy' operator

### ISSUE THREAD

**Issue by simonjscott** [dwestheide/kontextfrei#64]
Add partitionBy as defined by
`def partitionBy(partitioner: Partitioner): RDD[(K, V)]` in `PairRDDFunctions`

Also suggests addition of 'defaultPartitioner' to get the default partitioner of an RDD. Defined by 
`def defaultPartitioner(rdd: RDD[_], others: RDD[_]*): Partitioner` in `Partitioner`

**Comment by dwestheide** [comment]
Sounds good! Are you interested in implementing this? :)

**Comment by simonjscott** [comment]
Yes I have a proposed solution. Will get pull request over to you for review. :)

**Comment by dwestheide** [comment]
Cool! Looking forward to it! :)

**Comment by dwestheide** [comment]
Closed by #65

**Comment by dwestheide** [comment]
This has been released [kontextfrei 0.8.0](https://github.com/dwestheide/kontextfrei/releases/tag/v0.8.0)
