### ISSUE TITLE
Spark UI shows call site as kontextfrei

### ISSUE THREAD

**Issue by simonjscott** [dwestheide/kontextfrei#66]
Ordinarily, the Spark UI shows the call site for action methods called on an RDD. e.g. the Description column below

Job Id  ▾ | Description | Submitted | Duration | Stages: Succeeded/Total | Tasks (for all stages): Succeeded/Total
-- | -- | -- | -- | -- | --
8 | aggregate at AreaKpis.scala:292 | 2019/01/11 15:21:02 | 2.1 min | 3/3 (8 skipped) | 633/633 (4050 skipped)
7 | collect at Kpis.scala:179 | 2019/01/11 15:20:44 | 2 s | 1/1 (6 skipped) | 211/211 (3628 skipped)

When using kontextfrei, the call site is set to a method of kontextfrei - usually in RDDBaseFunctions, but can also be RDDPairFunctions, RDDOrderedFunctions. This obscures valuable information for the developer. The full call stack is available from a "details" link, but that is an extra click...

**Comment by dwestheide** [comment]
Yes, this is definitely annoying! Thanks for reporting and already implementing a fix. I am a bit busy right now, but I will try to look at your PR later today. :+1:

**Comment by dwestheide** [comment]
Resolved in #67

**Comment by dwestheide** [comment]
This has been released [kontextfrei 0.8.0](https://github.com/dwestheide/kontextfrei/releases/tag/v0.8.0)
